type = internal/xworkspaces

pin-workspaces = false

enable-click = true
enable-scroll = true

icon-0 = doc1;
icon-1 = doc2;
icon-2 = doc3;
icon-3 = dev;
icon-4 = sys;
icon-5 = conf;
icon-6 = chat;
icon-7 = www;
icon-8 = general;
icon-9 = media;

format-prefix = " "

format = <label-state>
format-background = ${colors.bg}
format-foreground = ${colors.fg}

label-active = 
label-active-font = 4
label-active-margin-right = 1

label-occupied = 
label-occupied-font = 4
label-occupied-margin-right = 1

label-urgent = %{F#9ED072}%{F-}
label-urgent-font = 4
label-urgent-padding = 2

label-empty = %icon%
label-empty-font = 4
label-empty-margin-right = 1

; vim: filetype=dosini
